import os
import json
from openai import OpenAI
from dotenv import load_dotenv

# Load environment variables from a .env file if present
# Always look for it one level up (in the project root)
dotenv_path = os.path.join(os.path.dirname(__file__), '../../.env')
load_dotenv(dotenv_path)

# Initialize the OpenAI client (requires GEMINI_API_KEY env variable)
api_key = os.environ.get("GEMINI_API_KEY")
if not api_key:
    raise ValueError("GEMINI_API_KEY is not set in the environment.")

client = OpenAI(
    api_key=api_key,
    base_url="https://generativelanguage.googleapis.com/v1beta/openai/"
)

def analyze_document(text: str, language: str = "English", role: str = "business") -> dict:
    """
    Sends the document text to OpenAI to generate a structured analysis: summary, risks, and clauses.
    """
    prompt = f"""
    Analyze this legal document. The user role is '{role}'.
    Provide the output in {language}.
    
    Structure your response as a strictly valid JSON object with the following schema:
    {{
      "summary": "A concise executive summary of the document for a non-lawyer.",
      "keyClauses": {{
        "payment": ["Extract relevant payment clauses here"],
        "termination": ["Extract termination clauses here"],
        "penalties": ["Extract penalty clauses here"],
        "other": ["Any other important clauses"]
      }},
      "riskHighlights": [
        {{
          "severity": "low", // Must be strictly "low", "medium", or "high"
          "title": "A short title for the risk",
          "detail": "Explanation of the risk and why it matters.",
          "documentReference": "Quote or section reference from the document, or empty string if none."
        }}
      ],
      "disclaimer": "This analysis is generated by AI and should not be considered as legal advice."
    }}
    
    Document text (first 50,000 chars):
    {text[:50000]}
    """
    
    response = client.chat.completions.create(
        model="gemini-flash-latest",
        messages=[{"role": "user", "content": prompt}],
        response_format={"type": "json_object"}
    )
    
    try:
        content = response.choices[0].message.content
        if content.startswith("```json"):
            content = content.replace("```json\n", "").replace("```", "")
        elif content.startswith("```"):
            content = content.replace("```\n", "").replace("```", "")
        return json.loads(content.strip())
    except json.JSONDecodeError:
        return {
            "summary": "Failed to parse analysis.",
            "keyClauses": {"payment": [], "termination": [], "penalties": [], "other": []},
            "riskHighlights": [],
            "disclaimer": "Failed to generate analysis."
        }

def chat_document(text: str, query: str, history: list) -> str:
    """
    Simulates a light RAG/context-injection Q&A model.
    """
    messages = [
        {"role": "system", "content": f"You are a helpful legal AI assistant. Use the following document text to answer the user's questions. If the answer is not in the text, say 'I cannot find this in the document.'\n\nDocument Text:\n{text[:50000]}"}
    ]
    
    # Append the prior chat history
    for msg in history:
        messages.append({"role": msg["role"], "content": msg["content"]})
        
    # Append the current query
    messages.append({"role": "user", "content": query})

    response = client.chat.completions.create(
        model="gemini-flash-latest",
        messages=messages
    )
    return response.choices[0].message.content
