"use client";

import { useCallback, useState } from "react";
import type { AnalysisResult } from "@/lib/analysis-schema";
import type { TabId } from "./types";

const TABS: { id: TabId; label: string }[] = [
  { id: "summary", label: "Summary" },
  { id: "clauses", label: "Key clauses" },
  { id: "risks", label: "Risk highlights" },
];

const clauseSections: { key: keyof AnalysisResult["keyClauses"]; label: string }[] = [
  { key: "payment", label: "Payment" },
  { key: "termination", label: "Termination" },
  { key: "penalties", label: "Penalties" },
  { key: "other", label: "Other" },
];

type AnalysisPanelProps = {
  analysis: AnalysisResult;
  tab: TabId;
  onTabChange: (tab: TabId) => void;
};

function downloadAnalysisJson(analysis: AnalysisResult) {
  const blob = new Blob([JSON.stringify(analysis, null, 2)], {
    type: "application/json",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "analysis.json";
  a.click();
  URL.revokeObjectURL(url);
}

export function AnalysisPanel({ analysis, tab, onTabChange }: AnalysisPanelProps) {
  const [copyState, setCopyState] = useState<"idle" | "copied" | "failed">("idle");
  const [exportState, setExportState] = useState<"idle" | "exporting" | "exported">("idle");

  const copyJson = useCallback(async () => {
    const text = JSON.stringify(analysis, null, 2);
    try {
      await navigator.clipboard.writeText(text);
      setCopyState("copied");
      setTimeout(() => setCopyState("idle"), 2000);
    } catch {
      setCopyState("failed");
      setTimeout(() => setCopyState("idle"), 2500);
    }
  }, [analysis]);

  const exportAsPdf = useCallback(async () => {
    setExportState("exporting");
    try {
      // Create a printable HTML version
      const printContent = `
        <!DOCTYPE html>
        <html>
        <head>
          <title>Legal Analysis Report</title>
          <style>
            body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            h1 { color: #1e293b; border-bottom: 3px solid #c9a227; padding-bottom: 10px; }
            h2 { color: #334155; margin-top: 30px; }
            h3 { color: #475569; margin-top: 20px; }
            .section { margin: 20px 0; }
            .risk-badge { display: inline-block; padding: 4px 12px; border-radius: 12px; font-size: 12px; font-weight: 600; }
            .risk-low { background: #dcfce7; color: #15803d; }
            .risk-medium { background: #fef3c7; color: #ca8a04; }
            .risk-high { background: #fee2e2; color: #b91c1c; }
            ul { line-height: 1.8; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 12px; }
          </style>
        </head>
        <body>
          <h1>Legal Document Analysis Report</h1>
          <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
          
          <div class="section">
            <h2>Summary</h2>
            <p>${analysis.summary}</p>
          </div>

          <div class="section">
            <h2>Key Clauses</h2>
            ${["payment", "termination", "penalties", "other"]
              .map((key) => {
                const clauses = analysis.keyClauses[key as keyof typeof analysis.keyClauses];
                if (!clauses || clauses.length === 0) return "";
                return `
                  <h3>${key.charAt(0).toUpperCase() + key.slice(1)}</h3>
                  <ul>${clauses.map((clause) => `<li>${clause}</li>`).join("")}</ul>
                `;
              })
              .join("")}
          </div>

          <div class="section">
            <h2>Risk Highlights</h2>
            ${["low", "medium", "high"]
              .map((severity) => {
                const risks = analysis.riskHighlights.filter(
                  (r) => r.severity === severity
                );
                if (risks.length === 0) return "";
                return `
                  <h3>
                    <span class="risk-badge risk-${severity}">${severity.toUpperCase()}</span> Risks
                  </h3>
                  <ul>
                    ${risks.map((r) => `<li><strong>${r.title}:</strong> ${r.description}</li>`).join("")}
                  </ul>
                `;
              })
              .join("")}
          </div>

          <div class="footer">
            <p>This analysis is generated by AI and should not be considered as legal advice. Please consult with a qualified legal professional for legal matters.</p>
          </div>
        </body>
        </html>
      `;

      // Open print dialog
      const printWindow = window.open("", "_blank");
      if (printWindow) {
        printWindow.document.write(printContent);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => {
          printWindow.print();
          setExportState("exported");
          setTimeout(() => setExportState("idle"), 2000);
        }, 250);
      }
    } catch {
      setExportState("idle");
    }
  }, [analysis]);

  return (
    <section className="mb-10 rounded-xl border border-slate-200 bg-[var(--card)] p-6 shadow-sm dark:border-slate-600">
      <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <h2 className="text-lg font-medium text-slate-900 dark:text-slate-100">
          Analysis
        </h2>
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => void copyJson()}
            className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 min-h-11 transition-smooth hover:bg-slate-50 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"
          >
            {copyState === "copied"
              ? "Copied!"
              : copyState === "failed"
                ? "Copy failed"
                : "Copy JSON"}
          </button>
          <button
            type="button"
            onClick={() => downloadAnalysisJson(analysis)}
            className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 min-h-11 transition-smooth hover:bg-slate-50 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"
          >
            Download JSON
          </button>
          <button
            type="button"
            onClick={() => void exportAsPdf()}
            disabled={exportState === "exporting"}
            className="rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-medium text-slate-700 min-h-11 transition-smooth hover:bg-slate-50 disabled:opacity-50 dark:border-slate-600 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"
          >
            {exportState === "exporting"
              ? "Preparing..."
              : exportState === "exported"
                ? "Exported!"
                : "Export PDF"}
          </button>
        </div>
      </div>

      <div
        role="tablist"
        aria-label="Analysis sections"
        className="flex flex-wrap gap-2 border-b border-slate-200 pb-3 dark:border-slate-600"
      >
        {TABS.map(({ id, label }) => {
          const selected = tab === id;
          return (
            <button
              key={id}
              type="button"
              role="tab"
              id={`tab-${id}`}
              aria-selected={selected}
              aria-controls={`panel-${id}`}
              tabIndex={selected ? 0 : -1}
              onClick={() => onTabChange(id)}
              onKeyDown={(e) => {
                if (e.key !== "ArrowRight" && e.key !== "ArrowLeft") return;
                e.preventDefault();
                const i = TABS.findIndex((t) => t.id === id);
                const next =
                  e.key === "ArrowRight"
                    ? TABS[(i + 1) % TABS.length]
                    : TABS[(i - 1 + TABS.length) % TABS.length];
                onTabChange(next.id);
                document.getElementById(`tab-${next.id}`)?.focus();
              }}
              className={`rounded-lg px-3 py-2 text-sm font-medium min-h-11 transition-colors ${
                selected
                  ? "bg-[var(--accent)] text-white"
                  : "bg-slate-100 text-slate-700 hover:bg-slate-200 dark:bg-slate-800 dark:text-slate-200 dark:hover:bg-slate-700"
              }`}
            >
              {label}
            </button>
          );
        })}
      </div>

      <div
        id="panel-summary"
        role="tabpanel"
        aria-labelledby="tab-summary"
        hidden={tab !== "summary"}
        className="mt-4 min-h-[120px] text-slate-800 dark:text-slate-200"
      >
        {tab === "summary" && (
          <p className="whitespace-pre-wrap leading-relaxed">{analysis.summary}</p>
        )}
      </div>
      <div
        id="panel-clauses"
        role="tabpanel"
        aria-labelledby="tab-clauses"
        hidden={tab !== "clauses"}
        className="mt-4 min-h-[120px] text-slate-800 dark:text-slate-200"
      >
        {tab === "clauses" && (
          <div className="space-y-6">
            {clauseSections.map(({ key, label }) => {
              const items = analysis.keyClauses[key] ?? [];
              if (!items.length) return null;
              return (
                <div key={key}>
                  <h3 className="mb-2 font-semibold text-slate-900 dark:text-slate-100">
                    {label}
                  </h3>
                  <ul className="list-inside list-disc space-y-1 text-sm leading-relaxed">
                    {items.map((item, i) => (
                      <li key={i}>{item}</li>
                    ))}
                  </ul>
                </div>
              );
            })}
            {clauseSections.every((s) => !(analysis.keyClauses[s.key] ?? []).length) && (
              <p className="text-slate-600 dark:text-slate-400">
                No key clauses were identified in the document.
              </p>
            )}
          </div>
        )}
      </div>
      <div
        id="panel-risks"
        role="tabpanel"
        aria-labelledby="tab-risks"
        hidden={tab !== "risks"}
        className="mt-4 min-h-[120px] text-slate-800 dark:text-slate-200"
      >
        {tab === "risks" && (
          <ul className="space-y-4">
            {analysis.riskHighlights.length === 0 && (
              <li className="text-slate-600 dark:text-slate-400">
                No risk highlights returned.
              </li>
            )}
            {analysis.riskHighlights.map((r, i) => (
              <li
                key={i}
                className="rounded-lg border border-slate-100 bg-slate-50/80 p-4 dark:border-slate-700 dark:bg-slate-800/80"
              >
                <div className="mb-1 flex flex-wrap items-center gap-2">
                  <span
                    className={`inline-flex rounded-full px-2 py-0.5 text-xs font-semibold uppercase tracking-wide ${
                      r.severity === "high"
                        ? "bg-red-100 text-[var(--risk-high)] dark:bg-red-950/50 dark:text-red-300"
                        : r.severity === "medium"
                          ? "bg-amber-100 text-[var(--risk-medium)] dark:bg-amber-950/50 dark:text-amber-300"
                          : "bg-emerald-100 text-[var(--risk-low)] dark:bg-emerald-950/50 dark:text-emerald-300"
                    }`}
                  >
                    {r.severity}
                  </span>
                  <span className="font-medium text-slate-900 dark:text-slate-100">
                    {r.title}
                  </span>
                </div>
                <p className="text-sm leading-relaxed text-slate-700 dark:text-slate-300">
                  {r.detail}
                </p>
                {r.documentReference && (
                  <p className="mt-2 text-xs text-slate-500 dark:text-slate-400">
                    Reference: {r.documentReference}
                  </p>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>

      <p className="mt-6 border-t border-slate-100 pt-4 text-xs text-slate-500 dark:border-slate-700 dark:text-slate-400">
        {analysis.disclaimer}
      </p>
    </section>
  );
}
